In [ ]:
aggregations in numpy

In [16]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr1

array([10, 20, 30, 40, 50])

In [17]:
arr2 = np.array([[0, 10, 20], [30, 40, 50], [60, 70, 80]])
arr2


array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [18]:
arr3 = np.array([[14, 6, 9, -12, 19, 72],[-9, 8, 22, 0, 99, -11]])
arr3

array([[ 14,   6,   9, -12,  19,  72],
       [ -9,   8,  22,   0,  99, -11]])

In [ ]:
sum function

In [23]:
arr1.sum(axis=0)

150

In [ ]:
average function

In [25]:
np.average(arr1)

30.0

In [26]:
np.average(arr3)

18.083333333333332

In [ ]:
Product 

In [28]:
np.prod(arr2)

0

In [29]:
y = np.random.randint(1, 10, size = (5, 5))
np.prod(y)

-2075787264

In [31]:
Min function

In [33]:
arr2.min(axis=0)

array([ 0, 10, 20])

In [34]:
arr2.min(axis=1)

array([ 0, 30, 60])

In [ ]:
max function

In [36]:
arr1.max()

50

In [37]:
arr3.max()

99

In [ ]:
mean function

In [38]:
arr2.mean()

40.0

In [39]:
arr1.mean()

30.0

median function

In [40]:
np.median(arr1)

30.0

In [41]:
np.median(arr2)

40.0

In [43]:
standard deviaton

In [44]:
arr1.std()

14.142135623730951

In [45]:
arr2.std()

25.81988897471611

In [ ]:
cumsum function

In [51]:
arr2.cumsum()

array([  0,  10,  30,  60, 100, 150, 210, 280, 360], dtype=int32)

In [52]:
arr2.cumsum(1)

array([[  0,  10,  30],
       [ 30,  70, 120],
       [ 60, 130, 210]], dtype=int32)

In [ ]:
cumprod

In [53]:
arr2.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [54]:
arr2.cumprod(1)

array([[     0,      0,      0],
       [    30,   1200,  60000],
       [    60,   4200, 336000]], dtype=int32)