In [2]:
import numpy as np

In [4]:
a= np.array([1, 2, 3, 4, 5])

In [5]:
a<4

array([ True,  True,  True, False, False])

In [6]:
a>4

array([False, False, False, False,  True])

In [8]:
a<=4

array([ True,  True,  True,  True, False])

In [9]:
a>=4

array([False, False, False,  True,  True])

In [10]:
a!=4

array([ True,  True,  True, False,  True])

In [12]:
a==4

array([False, False, False,  True, False])

In [14]:
(2*a)==(a**2)

array([False,  True, False, False, False])

In [ ]:
bool

In [16]:
r= np.random.RandomState(0)
x = r.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [17]:
x>4

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [18]:
np.count_nonzero(x < 4)

5

In [23]:
np.sum(x < 4)

5

In [24]:
np.any(x < 4)

True

In [25]:
np.all(x < 4)

False

In [26]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])